config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :addresses
  ActiveAdmin.routes(self)
  root "homes#index"
  get "products",to: "products#index"
  get  "products/:id", to: "products#show", as: "show"
  get "/homes", to: "homes#index"
  get "/categorys", to: "categorys#index"
  get "/orders", to: "orders#index"
  get "/addresses", to: "addresses#new"


  resource :articles
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_for :users
  get "/add_to_cart/:product_id", to: "products#add_to_cart"
  get "/remove_to_cart/:product_id", to: "products#remove_to_cart"
  get "/cart_clear", to: "products#cart_clear"


  get "/add_to_wishlist/:product_id", to: "products#add_to_wishlist"
  get "/remove_to_wishlist/:product_id", to: "products#remove_to_wishlist"

  get "/add_to_dolike/:product_id", to: "products#add_to_dolike"
  get "/remove_to_dolike/:product_id", to: "products#remove_to_dolike"
  get "/cancel/:order_id", to: "orders#cancel"


  get "/search", to: "products#search"
  get "carts",to: "carts#index"
  get "wishlists",to: "wishlists#index"
  get "dolikes",to: "dolikes#index"
  
  
  get "contacts", to: "contacts#index"
  get "shops", to: "shops#index"

  post "/create-checkout-session", to: "carts#checkout"

  get "/carts/success", to: "carts#success"
  get "/carts/cancel", to: "carts#cancel"
  get "/success", to: "carts#success_page"
  get "/cancel", to: "carts#cancel_page"
  
  resource :contacts
  resource :reviews

  # match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  # match '/auth/:provider/callback', :to => 'sessions#create'

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  acts_as_shopping_cart_using :cart_item
  belongs_to :user

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	acts_as_shopping_cart_item_for :cart

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :subcategory, dependent: :destroy
	
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dolike.rb
class Dolike < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	has_many :reviews

end

app/models/order_booking.rb
class OrderBooking < ApplicationRecord
	belongs_to :user
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	enum status: %i[created inprocess deliverd cancelled]
	enum refund: %i[progress refunded failed NotApplicabel]
end

app/models/preview.rb
class Preview < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord 
	# extend FriendlyId
 #  	friendly_id :name, use: :slugged
  	
	has_many :order_items
	belongs_to :subcategory
	validates :name, presence: true
	mount_uploader :image, ImageUploader
	has_many :reviews

	def calculate_discount(product)
		discount_price = (product.price.to_f*product.discount.to_f)/100.0
		return (product.price.to_f - discount_price.to_f)
	end
	
end

app/models/review.rb
class Review < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :user
	has_many :orders
	# belongs_to :product
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :wishlists  
  has_many :dolikes  
  has_many :order_bookings
  has_many :addresses
  has_many :feedbacks
  has_many :reviews
  
  has_many :authentications, dependent: :destroy
  validates :email, :uniqueness => {:allow_blank => true} 
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # skip_before_action :authenticate_user!
  def index
    if current_user.cart.present?
      @cart = current_user.cart
    else  
      @cart = Cart.create(user_id: current_user.id)
    end 
    @cart_items = @cart.cart_items
  end

  def checkout
    if params["order"]["cash_on_delivery"].present?
      OrderStatus.create(order_id: params[:order_id], refund: "NotApplicabel")
      @cart_items = Product.where(id: current_user.cart.cart_items.map(&:item_id))
      order = OrderBooking.new
      order.customer_email = current_user.email
      order.customer_id = current_user.id
      order.user_id = current_user.id
      order.product_id = current_user.cart.cart_items.map(&:item_id)
      order.amount_total = current_user.cart.subtotal
      order.address_id = params["order"]["address_id"]
      # order.customer_address_line_one = params["address"]["line1"]
      # order.customer_address_line_two = customer["address"]["line2"]
      # order.post_code = params["address"]["postal_code"]
      # order.customer_state = params["address"]["state"]
      # order.phone = params["address"]["phone"]
      order.cash_on_delivery = true
      order.save
      OrderStatus.create(order_id: params[:order_id], status: "created")
      current_user.cart.clear
      redirect_to "/success"
    else 
      Stripe.api_key = "sk_test_51KWwrwSJkerzRPBUxkXVy9PTD9clPnX2KrEycutGuZxdFULjpNu1W6Lev5jSpYUmCc99SumqCo3JKOUD2mYr2nvD00UY2qQ9hk"
      @session = Stripe::Checkout::Session.create({
        line_items: [{
          price_data: {
            currency: 'inr',
            product_data: {
              name: "#{current_user.cart.cart_items.map{|data| data.item.id}}",
            },
            
            unit_amount: (current_user.cart.subtotal.to_f*100.0).to_i,
          },
          quantity: 1,
        }],
       
        mode: 'payment',
        shipping_address_collection: {
          allowed_countries: ['IN'],
        },
        # These placeholder URLs will be replaced in a following step.
        success_url: "https://flip-cart-lite.herokuapp.com//carts/success?session_id={CHECKOUT_SESSION_ID}&product_ids=#{current_user.cart.cart_items.map(&:item_id)}&address_id=#{params["order"]["address_id"]}",
        cancel_url: 'https://flip-cart-lite.herokuapp.com//carts/cancel',
      })
      # http://localhost:3000
    end  
  end


  def success
    session = Stripe::Checkout::Session.retrieve(params[:session_id])
    customer = Stripe::Customer.retrieve(session.customer)
    @cart_items = Product.where(id: params[:product_ids].split(/\D+/).reject(&:empty?).map(&:to_i))
    order = OrderBooking.new
    order.customer_email = customer["email"]
    order.customer_id = customer["id"]
    order.user_id = current_user.id
    order.product_id = params[:product_ids].split(/\D+/).reject(&:empty?).map(&:to_i).to_a
    order.customer_city = customer["address"]["city"]
    order.customer_country = customer["address"]["country"]
    order.customer_address_line_one =  customer["address"]["line1"]
    order.customer_address_line_two = customer["address"]["line2"]
    order.post_code = customer["address"]["postal_code"]
    order.customer_state = customer["address"]["state"]
    order.phone = customer["phone"]
    order.payment_intent = session["payment_intent"]
    order.amount_total = session["amount_total"]
    order.address_id = params[:address_id]
    order.save
    OrderStatus.create(order_id: params[:order_id], status: "created")
    current_user.cart.clear
    redirect_to "/success"
  end

  def cancel
    redirect_to "/cancel"
  end
  
  def cancel_page
    
  end

  def success_page
    
  end

  def create
    @carts = Cart.create(name: params[:form][:name], email: params[:current_user.email])
    CartshopMailer.cart_mail(@carts).deliver_now 
    redirect_to homes_path
  end

  def address
    @address = Address.all
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/address.html.erb
<%= render 'addresses/form', address: @address %>

app/views/carts/cancel.html.erb
your order has been cancel

app/views/carts/cancel_page.html.erb
<div class="Order">
    <h2>Order has been canceled </h2>
    <h3><a href="/products" class="btn btn-info"> <i class="fa fa-arrow-left" aria-hidden="true"></i> Contuniue shopping </a></h3>
    <h3>if you have any problem contect us <span><a href="/contacts" class="btn btn-outline-warning"> Contact us</a></span></h3>
</div>
<style type="text/css">
  .Order{
    margin-top:130px ;
    text-align: center;
    margin-bottom: 180px;
  }
</style>

app/views/carts/checkout.html.erb
<script src="https://js.stripe.com/v3"></script>
<!-- <script src="https://js.stripe.com/v3/"></script> -->
<script type="text/javascript">
	<% session_id = @session.id %>
	<% Stripe.api_key = ENV["API_KEY"] %>

	jQuery(document).ready(function($) {
    var stripe = Stripe(ENV["SECRET_KEY"]);
    stripe.redirectToCheckout({ sessionId: "<%= @session.id %>" });
	});
</script>

app/views/carts/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<% if @cart.subtotal <= 0 %>
  <div class="cart">
     <h1 style="text-align: center;"> Your cart is Empty <br>
     <a href="/products" class="btn btn-warning "><i class="fa-brands fa-product-hunt"></i>Add Your product </a>
     </h1>
  </div>
<% else %>
<div class="container px-4 py-5 mx-auto">
<a href="/cart_clear/<% cart_clear_url %>" class="btn btn-danger">Empty Cart  <i class="fa fa-shopping-cart" aria-hidden="true"></i></a></hr>
<section class="h-100" style="background-color: #eee;">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">

        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
          
        </div>
        <% @cart_items.each do |product| %>
          <div class="card rounded-3 mb-4">
            <div class="card-body p-4">
              <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-2 col-lg-2 col-xl-2">
                  <%= image_tag product.item.image_url rescue nil%> 
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3">
                  <p class="lead fw-normal mb-2"><%= product.item.name %></p>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                  Quantity <%= product.quantity %>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                  <h5 class="mb-0">&#8377;<%= product.item.calculate_discount(product.item) %></h5>
                </div>
                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                  <a href="/remove_to_cart/<%= product.item.id %>" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <br>
        <strong>Select one Address </strong>
        <%= form_for "data", url: "/create-checkout-session" do |form| %>
          <% current_user.addresses.each do |ad|%>
            <p><input type="radio" name="order[address_id]" class="choose_address" value="<%= ad.id %>" required> <%= ad.state %> , <%= ad.line1%> , <%= ad.line2%> , <%= ad.phone%> , <%= ad.pincode%> , <%= ad.country%></p></li>
          <% end %>
           <a href="/addresses/new">Create new address</a>
          <% if current_user.addresses.present? %> 
            <div class="card">
              <div class="card-body">
                 <!-- <form action="/addresses" method="GET"> -->
                  <!-- <button type="submit" value = "dadad" class="btn btn-warning btn-block btn-lg"><i class="fa fa-shopping-bag" aria-hidden="true"></i> cash on delivery &#8377;<%#= @cart.subtotal %></button> -->
                  <input type="submit" name="order[cash_on_delivery]" class="btn btn-warning btn-block btn-lg" value="cash on delivery &#8377;<%= @cart.subtotal %>" />
                <!-- </form> -->
                <br>
                <!-- <form action="/create-checkout-session" method="POST"> -->
                  <button type="submit" class="btn btn-warning btn-block btn-lg"><i class="fa fa-shopping-bag" aria-hidden="true"></i> Checkout &#8377;<%= @cart.subtotal %></button>
                <!-- </form> -->
              </div>
            </div>
          <% end %>  
        <% end %>  
      </div>
    </div>
  </div>
</section>
<% end %>
<script type="text/javascript">
  $(function(){
    $("input[type='radio']").change(function(){
      $("input[type='submit']").prop("disabled", false);
    });
  });
  $(document).ready(function(){
    $("input").prop('required', true);
    $("text_field").prop('required', true);
  });
</script>
<style type="text/css">
  .cart{
  margin-top: 11%;
  margin-bottom: 15%;
  height: 100%;
  width: 100%;
}
 img {
    
    height: 50px;
    width: 80px;
}
</style>

app/views/carts/success.html.erb
THnaks For your order

app/views/carts/success_page.html.erb
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 0px 0;
        background: powderblue;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      .card i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 30px;
        /*box-shadow: 1px 2px 3px 7px #5c5757;*/
        display: inline-block;
        margin: 10px auto;
      }

	.btn-info:hover {
	  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
	}
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Successful</h1> 
        <p>Thanks for your order<br/> </p>
        <a href="/products" class="btn btn-info" style="background-color: green; border-radius: 15px;">Click here for more shopping </a>
      </div>
    </body>
</html>