config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :addresses
  ActiveAdmin.routes(self)
  root "homes#index"
  get "products",to: "products#index"
  get  "products/:id", to: "products#show", as: "show"
  get "/homes", to: "homes#index"
  get "/categorys", to: "categorys#index"
  get "/orders", to: "orders#index"
  get "/addresses", to: "addresses#new"


  resource :articles
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  devise_for :users
  get "/add_to_cart/:product_id", to: "products#add_to_cart"
  get "/remove_to_cart/:product_id", to: "products#remove_to_cart"
  get "/cart_clear", to: "products#cart_clear"


  get "/add_to_wishlist/:product_id", to: "products#add_to_wishlist"
  get "/remove_to_wishlist/:product_id", to: "products#remove_to_wishlist"

  get "/add_to_dolike/:product_id", to: "products#add_to_dolike"
  get "/remove_to_dolike/:product_id", to: "products#remove_to_dolike"
  get "/cancel/:order_id", to: "orders#cancel"


  get "/search", to: "products#search"
  get "carts",to: "carts#index"
  get "wishlists",to: "wishlists#index"
  get "dolikes",to: "dolikes#index"
  
  
  get "contacts", to: "contacts#index"
  get "shops", to: "shops#index"

  post "/create-checkout-session", to: "carts#checkout"

  get "/carts/success", to: "carts#success"
  get "/carts/cancel", to: "carts#cancel"
  get "/success", to: "carts#success_page"
  get "/cancel", to: "carts#cancel_page"
  
  resource :contacts
  resource :reviews

  # match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  # match '/auth/:provider/callback', :to => 'sessions#create'

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  acts_as_shopping_cart_using :cart_item
  belongs_to :user

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	acts_as_shopping_cart_item_for :cart

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :subcategory, dependent: :destroy
	
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dolike.rb
class Dolike < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	has_many :reviews

end

app/models/order_booking.rb
class OrderBooking < ApplicationRecord
	belongs_to :user
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	enum status: %i[created inprocess deliverd cancelled]
	enum refund: %i[progress refunded failed NotApplicabel]
end

app/models/preview.rb
class Preview < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord 
	# extend FriendlyId
 #  	friendly_id :name, use: :slugged
  	
	has_many :order_items
	belongs_to :subcategory
	validates :name, presence: true
	mount_uploader :image, ImageUploader
	has_many :reviews

	def calculate_discount(product)
		discount_price = (product.price.to_f*product.discount.to_f)/100.0
		return (product.price.to_f - discount_price.to_f)
	end
	
end

app/models/review.rb
class Review < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :user
	has_many :orders
	# belongs_to :product
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
	belongs_to :category
	has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
  has_many :wishlists  
  has_many :dolikes  
  has_many :order_bookings
  has_many :addresses
  has_many :feedbacks
  has_many :reviews
  
  has_many :authentications, dependent: :destroy
  validates :email, :uniqueness => {:allow_blank => true} 
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < InheritedResources::Base
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
    @feedback = Feedback.find_by(id: params[:id])
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
    render layout: false
  end

  # def create

  # @user = User.new(user_params)

  # if @user.save
  #     flash[:notice] = "You have signed up successdully"
  #     flash[:color] = "valid"
  # else
  #     flash[:notice] = "Invalid Input!"
  #     flash[:color] = "invalid"
  #     render "new"
  # end


  # GET /feedbacks/1/edit
  def edit
  end

  private

    def feedback_params
      params.require(:feedback).permit(:product_id, :user_id, :body, :rate)
    end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback, local: true) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.number_field :rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>User</th>
      <th>Body</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.product_id %></td>
        <td><%= feedback.user_id %></td>
        <td><%= feedback.body %></td>
        <td><%= feedback.rate %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @feedback.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @feedback.body %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @feedback.rate %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>